# Generated by Django 3.0.8 on 2020-07-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.IntegerField(choices=[(0, 'Seriki Oluwaranti'), (1, 'Seriki Ayo')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image1', models.ImageField(blank=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, upload_to='images/')),
                ('category', models.IntegerField(choices=[(0, 'News'), (1, 'Entertainment'), (2, 'Sports'), (3, 'WorldNews')], default=0)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
